# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReconGUI.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IMXReconGUI(object):
    def setupUi(self, IMXReconGUI):
        IMXReconGUI.setObjectName("IMXReconGUI")
        IMXReconGUI.resize(873, 623)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/MainWindowIcon/Images/LNLS_logo_mini.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        IMXReconGUI.setWindowIcon(icon)
        IMXReconGUI.setStyleSheet("background-color:rgb(234, 234, 234)")
        self.centralwidget = QtWidgets.QWidget(IMXReconGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 6)
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 3, 4, 5, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.FilePathLabel = QtWidgets.QLabel(self.centralwidget)
        self.FilePathLabel.setObjectName("FilePathLabel")
        self.horizontalLayout_3.addWidget(self.FilePathLabel)
        self.FilePathLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.FilePathLineEdit.setEnabled(False)
        self.FilePathLineEdit.setObjectName("FilePathLineEdit")
        self.horizontalLayout_3.addWidget(self.FilePathLineEdit)
        self.FilePathChooseButton = QtWidgets.QPushButton(self.centralwidget)
        self.FilePathChooseButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FilePathChooseButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/FolderIcon/Images/closed_folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FilePathChooseButton.setIcon(icon1)
        self.FilePathChooseButton.setObjectName("FilePathChooseButton")
        self.horizontalLayout_3.addWidget(self.FilePathChooseButton)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.MoreOptionsLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.MoreOptionsLabel.setFont(font)
        self.MoreOptionsLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MoreOptionsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MoreOptionsLabel.setObjectName("MoreOptionsLabel")
        self.verticalLayout.addWidget(self.MoreOptionsLabel)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.OpenSinogramButton = QtWidgets.QPushButton(self.centralwidget)
        self.OpenSinogramButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.OpenSinogramButton.setObjectName("OpenSinogramButton")
        self.gridLayout_3.addWidget(self.OpenSinogramButton, 0, 1, 1, 1)
        self.H5OptionsButton = QtWidgets.QPushButton(self.centralwidget)
        self.H5OptionsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.H5OptionsButton.setObjectName("H5OptionsButton")
        self.gridLayout_3.addWidget(self.H5OptionsButton, 0, 3, 1, 1)
        self.OpenProjectionButton = QtWidgets.QPushButton(self.centralwidget)
        self.OpenProjectionButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.OpenProjectionButton.setObjectName("OpenProjectionButton")
        self.gridLayout_3.addWidget(self.OpenProjectionButton, 0, 0, 1, 1)
        self.OpenFolderButton = QtWidgets.QPushButton(self.centralwidget)
        self.OpenFolderButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.OpenFolderButton.setObjectName("OpenFolderButton")
        self.gridLayout_3.addWidget(self.OpenFolderButton, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 7, 3, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 3, 2, 5, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ExperimentInformationLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ExperimentInformationLabel.setFont(font)
        self.ExperimentInformationLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ExperimentInformationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ExperimentInformationLabel.setObjectName("ExperimentInformationLabel")
        self.verticalLayout_3.addWidget(self.ExperimentInformationLabel)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout_3)
        self.AngleRangeLabel = QtWidgets.QLabel(self.centralwidget)
        self.AngleRangeLabel.setObjectName("AngleRangeLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.AngleRangeLabel)
        self.AngleRangeValue = QtWidgets.QLabel(self.centralwidget)
        self.AngleRangeValue.setAlignment(QtCore.Qt.AlignCenter)
        self.AngleRangeValue.setObjectName("AngleRangeValue")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.AngleRangeValue)
        self.NumberofProjectionsLabel = QtWidgets.QLabel(self.centralwidget)
        self.NumberofProjectionsLabel.setObjectName("NumberofProjectionsLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.NumberofProjectionsLabel)
        self.NumberofProjectionsValue = QtWidgets.QLabel(self.centralwidget)
        self.NumberofProjectionsValue.setAlignment(QtCore.Qt.AlignCenter)
        self.NumberofProjectionsValue.setObjectName("NumberofProjectionsValue")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.NumberofProjectionsValue)
        self.ExposureTimeLabel = QtWidgets.QLabel(self.centralwidget)
        self.ExposureTimeLabel.setObjectName("ExposureTimeLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ExposureTimeLabel)
        self.ExposureTimeValue = QtWidgets.QLabel(self.centralwidget)
        self.ExposureTimeValue.setAlignment(QtCore.Qt.AlignCenter)
        self.ExposureTimeValue.setObjectName("ExposureTimeValue")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ExposureTimeValue)
        self.DetectorPositionLabel = QtWidgets.QLabel(self.centralwidget)
        self.DetectorPositionLabel.setObjectName("DetectorPositionLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.DetectorPositionLabel)
        self.DetectorPositionValue = QtWidgets.QLabel(self.centralwidget)
        self.DetectorPositionValue.setAlignment(QtCore.Qt.AlignCenter)
        self.DetectorPositionValue.setObjectName("DetectorPositionValue")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.DetectorPositionValue)
        self.FiltersLabel = QtWidgets.QLabel(self.centralwidget)
        self.FiltersLabel.setObjectName("FiltersLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.FiltersLabel)
        self.FilterValue = QtWidgets.QLabel(self.centralwidget)
        self.FilterValue.setAlignment(QtCore.Qt.AlignCenter)
        self.FilterValue.setObjectName("FilterValue")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.FilterValue)
        self.PixelSizeLabel = QtWidgets.QLabel(self.centralwidget)
        self.PixelSizeLabel.setObjectName("PixelSizeLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.PixelSizeLabel)
        self.PixelSizeValue = QtWidgets.QLabel(self.centralwidget)
        self.PixelSizeValue.setAlignment(QtCore.Qt.AlignCenter)
        self.PixelSizeValue.setObjectName("PixelSizeValue")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.PixelSizeValue)
        self.FieldofViewLabel = QtWidgets.QLabel(self.centralwidget)
        self.FieldofViewLabel.setObjectName("FieldofViewLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.FieldofViewLabel)
        self.FieldofViewValue = QtWidgets.QLabel(self.centralwidget)
        self.FieldofViewValue.setAlignment(QtCore.Qt.AlignCenter)
        self.FieldofViewValue.setObjectName("FieldofViewValue")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.FieldofViewValue)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.MoreInfoButton = QtWidgets.QPushButton(self.centralwidget)
        self.MoreInfoButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MoreInfoButton.setObjectName("MoreInfoButton")
        self.verticalLayout_2.addWidget(self.MoreInfoButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem)
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_2.addWidget(self.line_10)
        self.formLayout.setLayout(8, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout_2)
        self.ReconMethodLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ReconMethodLabel.setFont(font)
        self.ReconMethodLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ReconMethodLabel.setObjectName("ReconMethodLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.ReconMethodLabel)
        self.RAfTLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.RAfTLabel.setFont(font)
        self.RAfTLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.RAfTLabel.setObjectName("RAfTLabel")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.RAfTLabel)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.SpanningRole, self.line_6)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_12.addItem(spacerItem1)
        self.OpenImageLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.OpenImageLabel.setFont(font)
        self.OpenImageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.OpenImageLabel.setObjectName("OpenImageLabel")
        self.verticalLayout_12.addWidget(self.OpenImageLabel)
        self.OpenImageComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.OpenImageComboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.OpenImageComboBox.setObjectName("OpenImageComboBox")
        self.verticalLayout_12.addWidget(self.OpenImageComboBox)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.OpenImageButton = QtWidgets.QPushButton(self.centralwidget)
        self.OpenImageButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ImageJ/Images/ImageJ.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OpenImageButton.setIcon(icon2)
        self.OpenImageButton.setObjectName("OpenImageButton")
        self.horizontalLayout_6.addWidget(self.OpenImageButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.formLayout.setLayout(12, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout_12)
        self.gridLayout.addLayout(self.formLayout, 3, 0, 5, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.IMXGUINameLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.IMXGUINameLabel.setFont(font)
        self.IMXGUINameLabel.setAutoFillBackground(False)
        self.IMXGUINameLabel.setObjectName("IMXGUINameLabel")
        self.horizontalLayout_2.addWidget(self.IMXGUINameLabel)
        self.LNLSLogoImageLabel = QtWidgets.QLabel(self.centralwidget)
        self.LNLSLogoImageLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.LNLSLogoImageLabel.setText("")
        self.LNLSLogoImageLabel.setPixmap(QtGui.QPixmap(":/MainWindowIcon/Images/LNLS_logo_mini.jpg"))
        self.LNLSLogoImageLabel.setObjectName("LNLSLogoImageLabel")
        self.horizontalLayout_2.addWidget(self.LNLSLogoImageLabel)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 6)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.CloseGuiButton = QtWidgets.QPushButton(self.centralwidget)
        self.CloseGuiButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CloseGuiButton.setObjectName("CloseGuiButton")
        self.gridLayout_2.addWidget(self.CloseGuiButton, 1, 2, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(False)
        self.progressBar.setStyleSheet("Base:rgb(0, 85, 255)")
        self.progressBar.setProperty("value", 100)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 1, 1, 1, 1)
        self.ProgressLabel = QtWidgets.QLabel(self.centralwidget)
        self.ProgressLabel.setObjectName("ProgressLabel")
        self.gridLayout_2.addWidget(self.ProgressLabel, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 10, 0, 1, 6)
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 9, 0, 1, 6)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.ReconQueueLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ReconQueueLabel.setFont(font)
        self.ReconQueueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ReconQueueLabel.setObjectName("ReconQueueLabel")
        self.verticalLayout_8.addWidget(self.ReconQueueLabel)
        self.ReconQueueTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.ReconQueueTextEdit.setObjectName("ReconQueueTextEdit")
        self.verticalLayout_8.addWidget(self.ReconQueueTextEdit)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.StartQueueButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartQueueButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.StartQueueButton.setObjectName("StartQueueButton")
        self.horizontalLayout_4.addWidget(self.StartQueueButton)
        self.StopQueueButton = QtWidgets.QPushButton(self.centralwidget)
        self.StopQueueButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.StopQueueButton.setObjectName("StopQueueButton")
        self.horizontalLayout_4.addWidget(self.StopQueueButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_8, 3, 5, 5, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.StartSliceLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.StartSliceLineEdit.setObjectName("StartSliceLineEdit")
        self.gridLayout_4.addWidget(self.StartSliceLineEdit, 1, 4, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_4.addWidget(self.line_7, 6, 2, 5, 1)
        self.CenteringLabel = QtWidgets.QLabel(self.centralwidget)
        self.CenteringLabel.setObjectName("CenteringLabel")
        self.gridLayout_4.addWidget(self.CenteringLabel, 2, 0, 1, 1)
        self.StartSliceLabel = QtWidgets.QLabel(self.centralwidget)
        self.StartSliceLabel.setObjectName("StartSliceLabel")
        self.gridLayout_4.addWidget(self.StartSliceLabel, 1, 3, 1, 1)
        self.ThresholdLabel = QtWidgets.QLabel(self.centralwidget)
        self.ThresholdLabel.setObjectName("ThresholdLabel")
        self.gridLayout_4.addWidget(self.ThresholdLabel, 6, 0, 1, 1)
        self.ThresholdLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ThresholdLineEdit.setObjectName("ThresholdLineEdit")
        self.gridLayout_4.addWidget(self.ThresholdLineEdit, 6, 1, 1, 1)
        self.RegularizationLabel = QtWidgets.QLabel(self.centralwidget)
        self.RegularizationLabel.setObjectName("RegularizationLabel")
        self.gridLayout_4.addWidget(self.RegularizationLabel, 6, 3, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.BasicParametersLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.BasicParametersLabel.setFont(font)
        self.BasicParametersLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.BasicParametersLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.BasicParametersLabel.setObjectName("BasicParametersLabel")
        self.verticalLayout_4.addWidget(self.BasicParametersLabel)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 0, 0, 1, 5)
        self.RegularizationLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.RegularizationLineEdit.setObjectName("RegularizationLineEdit")
        self.gridLayout_4.addWidget(self.RegularizationLineEdit, 6, 4, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 4, 0, 1, 5)
        self.RotationShiftLabel = QtWidgets.QLabel(self.centralwidget)
        self.RotationShiftLabel.setObjectName("RotationShiftLabel")
        self.gridLayout_4.addWidget(self.RotationShiftLabel, 1, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.AdvancedParametersLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AdvancedParametersLabel.setFont(font)
        self.AdvancedParametersLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AdvancedParametersLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.AdvancedParametersLabel.setObjectName("AdvancedParametersLabel")
        self.verticalLayout_7.addWidget(self.AdvancedParametersLabel)
        self.gridLayout_4.addLayout(self.verticalLayout_7, 5, 0, 1, 5)
        self.FinalSliceLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.FinalSliceLineEdit.setObjectName("FinalSliceLineEdit")
        self.gridLayout_4.addWidget(self.FinalSliceLineEdit, 2, 4, 1, 1)
        self.FinalSliceLabel = QtWidgets.QLabel(self.centralwidget)
        self.FinalSliceLabel.setObjectName("FinalSliceLabel")
        self.gridLayout_4.addWidget(self.FinalSliceLabel, 2, 3, 1, 1)
        self.RotationShiftLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.RotationShiftLineEdit.setObjectName("RotationShiftLineEdit")
        self.gridLayout_4.addWidget(self.RotationShiftLineEdit, 1, 1, 1, 1)
        self.CenteringLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.CenteringLineEdit.setObjectName("CenteringLineEdit")
        self.gridLayout_4.addWidget(self.CenteringLineEdit, 2, 1, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_4.addWidget(self.line_5, 11, 0, 1, 5)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_4.addWidget(self.line_4, 1, 2, 3, 1)
        self.NumberofBlocksSlider = QtWidgets.QSlider(self.centralwidget)
        self.NumberofBlocksSlider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.NumberofBlocksSlider.setMinimum(1)
        self.NumberofBlocksSlider.setMaximum(5)
        self.NumberofBlocksSlider.setPageStep(0)
        self.NumberofBlocksSlider.setProperty("value", 1)
        self.NumberofBlocksSlider.setOrientation(QtCore.Qt.Horizontal)
        self.NumberofBlocksSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.NumberofBlocksSlider.setObjectName("NumberofBlocksSlider")
        self.gridLayout_4.addWidget(self.NumberofBlocksSlider, 9, 4, 1, 1)
        self.ImageFormatLabel = QtWidgets.QLabel(self.centralwidget)
        self.ImageFormatLabel.setObjectName("ImageFormatLabel")
        self.gridLayout_4.addWidget(self.ImageFormatLabel, 7, 3, 1, 1)
        self.NumberofBlocksLabel = QtWidgets.QLabel(self.centralwidget)
        self.NumberofBlocksLabel.setObjectName("NumberofBlocksLabel")
        self.gridLayout_4.addWidget(self.NumberofBlocksLabel, 9, 3, 1, 1)
        self.SaveImageAsLabel = QtWidgets.QLabel(self.centralwidget)
        self.SaveImageAsLabel.setObjectName("SaveImageAsLabel")
        self.gridLayout_4.addWidget(self.SaveImageAsLabel, 8, 0, 1, 1)
        self.SaveImageAsComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.SaveImageAsComboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SaveImageAsComboBox.setObjectName("SaveImageAsComboBox")
        self.SaveImageAsComboBox.addItem("")
        self.SaveImageAsComboBox.addItem("")
        self.gridLayout_4.addWidget(self.SaveImageAsComboBox, 8, 1, 1, 1)
        self.ImageSizeLabel = QtWidgets.QLabel(self.centralwidget)
        self.ImageSizeLabel.setObjectName("ImageSizeLabel")
        self.gridLayout_4.addWidget(self.ImageSizeLabel, 7, 0, 1, 1)
        self.FilterCompositionLabel = QtWidgets.QLabel(self.centralwidget)
        self.FilterCompositionLabel.setObjectName("FilterCompositionLabel")
        self.gridLayout_4.addWidget(self.FilterCompositionLabel, 9, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.PreviewReconButton = QtWidgets.QPushButton(self.centralwidget)
        self.PreviewReconButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PreviewReconButton.setObjectName("PreviewReconButton")
        self.horizontalLayout.addWidget(self.PreviewReconButton)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.gridLayout_4.addLayout(self.horizontalLayout, 3, 3, 1, 2)
        self.FilterCompositionSlider = QtWidgets.QSlider(self.centralwidget)
        self.FilterCompositionSlider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FilterCompositionSlider.setMaximum(5)
        self.FilterCompositionSlider.setPageStep(0)
        self.FilterCompositionSlider.setProperty("value", 1)
        self.FilterCompositionSlider.setOrientation(QtCore.Qt.Horizontal)
        self.FilterCompositionSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.FilterCompositionSlider.setObjectName("FilterCompositionSlider")
        self.gridLayout_4.addWidget(self.FilterCompositionSlider, 9, 1, 1, 1)
        self.ImageFormaComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.ImageFormaComboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ImageFormaComboBox.setObjectName("ImageFormaComboBox")
        self.ImageFormaComboBox.addItem("")
        self.ImageFormaComboBox.addItem("")
        self.gridLayout_4.addWidget(self.ImageFormaComboBox, 7, 4, 1, 1)
        self.ImageSizeComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.ImageSizeComboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ImageSizeComboBox.setObjectName("ImageSizeComboBox")
        self.ImageSizeComboBox.addItem("")
        self.ImageSizeComboBox.addItem("")
        self.ImageSizeComboBox.addItem("")
        self.gridLayout_4.addWidget(self.ImageSizeComboBox, 7, 1, 1, 1)
        self.PaddingLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.PaddingLineEdit.setObjectName("PaddingLineEdit")
        self.gridLayout_4.addWidget(self.PaddingLineEdit, 8, 4, 1, 1)
        self.PaddingLabel = QtWidgets.QLabel(self.centralwidget)
        self.PaddingLabel.setObjectName("PaddingLabel")
        self.gridLayout_4.addWidget(self.PaddingLabel, 8, 3, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.AdjustSinoButton = QtWidgets.QPushButton(self.centralwidget)
        self.AdjustSinoButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AdjustSinoButton.setObjectName("AdjustSinoButton")
        self.horizontalLayout_5.addWidget(self.AdjustSinoButton)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 3, 0, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_4, 3, 3, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout.addWidget(self.line_11, 6, 3, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 8, 3, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.PositionQueue = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(10)
        self.PositionQueue.setFont(font)
        self.PositionQueue.setAlignment(QtCore.Qt.AlignCenter)
        self.PositionQueue.setObjectName("PositionQueue")
        self.gridLayout_11.addWidget(self.PositionQueue, 0, 1, 1, 1)
        self.PositionLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PositionLabel.setFont(font)
        self.PositionLabel.setObjectName("PositionLabel")
        self.gridLayout_11.addWidget(self.PositionLabel, 0, 0, 1, 1)
        self.DownPositionQueueButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DownPositionQueueButton.sizePolicy().hasHeightForWidth())
        self.DownPositionQueueButton.setSizePolicy(sizePolicy)
        self.DownPositionQueueButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DownPositionQueueButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Arrows/Images/rsz_red_arrow_downsvg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DownPositionQueueButton.setIcon(icon3)
        self.DownPositionQueueButton.setObjectName("DownPositionQueueButton")
        self.gridLayout_11.addWidget(self.DownPositionQueueButton, 0, 3, 1, 1)
        self.UpPositionQueueButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UpPositionQueueButton.sizePolicy().hasHeightForWidth())
        self.UpPositionQueueButton.setSizePolicy(sizePolicy)
        self.UpPositionQueueButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.UpPositionQueueButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Arrows/Images/rsz_greenarrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UpPositionQueueButton.setIcon(icon4)
        self.UpPositionQueueButton.setObjectName("UpPositionQueueButton")
        self.gridLayout_11.addWidget(self.UpPositionQueueButton, 0, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_11, 1, 0, 2, 1)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.CleanQueueButton = QtWidgets.QPushButton(self.centralwidget)
        self.CleanQueueButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CleanQueueButton.setObjectName("CleanQueueButton")
        self.verticalLayout_15.addWidget(self.CleanQueueButton)
        self.RemoveFromQueueButton = QtWidgets.QPushButton(self.centralwidget)
        self.RemoveFromQueueButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RemoveFromQueueButton.setObjectName("RemoveFromQueueButton")
        self.verticalLayout_15.addWidget(self.RemoveFromQueueButton)
        self.verticalLayout_18.addLayout(self.verticalLayout_15)
        self.gridLayout_10.addLayout(self.verticalLayout_18, 1, 2, 2, 1)
        self.AddReconQueueButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddReconQueueButton.sizePolicy().hasHeightForWidth())
        self.AddReconQueueButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AddReconQueueButton.setFont(font)
        self.AddReconQueueButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AddReconQueueButton.setObjectName("AddReconQueueButton")
        self.gridLayout_10.addWidget(self.AddReconQueueButton, 1, 1, 2, 1)
        self.QueueSettingsLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.QueueSettingsLabel.setFont(font)
        self.QueueSettingsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.QueueSettingsLabel.setObjectName("QueueSettingsLabel")
        self.gridLayout_10.addWidget(self.QueueSettingsLabel, 0, 0, 1, 3)
        self.gridLayout.addLayout(self.gridLayout_10, 5, 3, 1, 1)
        IMXReconGUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(IMXReconGUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 27))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        IMXReconGUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(IMXReconGUI)
        self.statusbar.setObjectName("statusbar")
        IMXReconGUI.setStatusBar(self.statusbar)
        self.actionVersion = QtWidgets.QAction(IMXReconGUI)
        self.actionVersion.setObjectName("actionVersion")
        self.actionContact = QtWidgets.QAction(IMXReconGUI)
        self.actionContact.setObjectName("actionContact")
        self.menuAbout.addAction(self.actionContact)
        self.menuAbout.addAction(self.actionVersion)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(IMXReconGUI)
        self.CloseGuiButton.clicked.connect(IMXReconGUI.close)
        self.PreviewReconButton.clicked.connect(self.progressBar.show)
        QtCore.QMetaObject.connectSlotsByName(IMXReconGUI)

    def retranslateUi(self, IMXReconGUI):
        _translate = QtCore.QCoreApplication.translate
        IMXReconGUI.setWindowTitle(_translate("IMXReconGUI", "IMX Recon GUI"))
        self.FilePathLabel.setText(_translate("IMXReconGUI", "File Path"))
        self.MoreOptionsLabel.setText(_translate("IMXReconGUI", "More Options"))
        self.OpenSinogramButton.setText(_translate("IMXReconGUI", "Sinogram"))
        self.H5OptionsButton.setText(_translate("IMXReconGUI", "H5 Options"))
        self.OpenProjectionButton.setText(_translate("IMXReconGUI", "Projection"))
        self.OpenFolderButton.setText(_translate("IMXReconGUI", "Folder"))
        self.ExperimentInformationLabel.setText(_translate("IMXReconGUI", "Experiment Information"))
        self.AngleRangeLabel.setText(_translate("IMXReconGUI", "Angle Range"))
        self.AngleRangeValue.setText(_translate("IMXReconGUI", "Waiting..."))
        self.NumberofProjectionsLabel.setText(_translate("IMXReconGUI", "# of Projections"))
        self.NumberofProjectionsValue.setText(_translate("IMXReconGUI", "Waiting..."))
        self.ExposureTimeLabel.setText(_translate("IMXReconGUI", "Exposure Time"))
        self.ExposureTimeValue.setText(_translate("IMXReconGUI", "Waiting..."))
        self.DetectorPositionLabel.setText(_translate("IMXReconGUI", "Detector Position"))
        self.DetectorPositionValue.setText(_translate("IMXReconGUI", "Waiting..."))
        self.FiltersLabel.setText(_translate("IMXReconGUI", "Filters"))
        self.FilterValue.setText(_translate("IMXReconGUI", "Waiting..."))
        self.PixelSizeLabel.setText(_translate("IMXReconGUI", "Pixel Size"))
        self.PixelSizeValue.setText(_translate("IMXReconGUI", "Waiting..."))
        self.FieldofViewLabel.setText(_translate("IMXReconGUI", "Field of View"))
        self.FieldofViewValue.setText(_translate("IMXReconGUI", "Waiting..."))
        self.MoreInfoButton.setText(_translate("IMXReconGUI", "More Info"))
        self.ReconMethodLabel.setText(_translate("IMXReconGUI", "Recon Method"))
        self.RAfTLabel.setText(_translate("IMXReconGUI", "<html><head/><body><p><span style=\" color:#0055ff;\">RAfT</span></p></body></html>"))
        self.OpenImageLabel.setText(_translate("IMXReconGUI", "Image"))
        self.OpenImageButton.setText(_translate("IMXReconGUI", "Open"))
        self.IMXGUINameLabel.setText(_translate("IMXReconGUI", "IMX Tomography Reconstruction User Interface"))
        self.CloseGuiButton.setText(_translate("IMXReconGUI", "Close"))
        self.ProgressLabel.setText(_translate("IMXReconGUI", "Wait. Reconstruction in process..."))
        self.ReconQueueLabel.setText(_translate("IMXReconGUI", "Recon Queue"))
        self.StartQueueButton.setText(_translate("IMXReconGUI", "Start Queue"))
        self.StopQueueButton.setText(_translate("IMXReconGUI", "Stop Queue"))
        self.StartSliceLineEdit.setText(_translate("IMXReconGUI", "1024"))
        self.CenteringLabel.setText(_translate("IMXReconGUI", "Centering (Only 360º)"))
        self.StartSliceLabel.setText(_translate("IMXReconGUI", "Start Slice"))
        self.ThresholdLabel.setText(_translate("IMXReconGUI", "Theshold"))
        self.ThresholdLineEdit.setText(_translate("IMXReconGUI", "15"))
        self.RegularizationLabel.setText(_translate("IMXReconGUI", "Regularization Factor"))
        self.BasicParametersLabel.setText(_translate("IMXReconGUI", "Basic Parameters"))
        self.RegularizationLineEdit.setText(_translate("IMXReconGUI", "0.00"))
        self.RotationShiftLabel.setText(_translate("IMXReconGUI", "Rotation Shift"))
        self.AdvancedParametersLabel.setText(_translate("IMXReconGUI", "Advanced Parameters"))
        self.FinalSliceLineEdit.setText(_translate("IMXReconGUI", "1024"))
        self.FinalSliceLabel.setText(_translate("IMXReconGUI", "Final Slice"))
        self.RotationShiftLineEdit.setText(_translate("IMXReconGUI", "0"))
        self.CenteringLineEdit.setText(_translate("IMXReconGUI", "1700"))
        self.ImageFormatLabel.setText(_translate("IMXReconGUI", "Image Format"))
        self.NumberofBlocksLabel.setText(_translate("IMXReconGUI", "Number of Blocks"))
        self.SaveImageAsLabel.setText(_translate("IMXReconGUI", "Save Slices as"))
        self.SaveImageAsComboBox.setItemText(0, _translate("IMXReconGUI", "Block"))
        self.SaveImageAsComboBox.setItemText(1, _translate("IMXReconGUI", "Single Files"))
        self.ImageSizeLabel.setText(_translate("IMXReconGUI", "Image Size"))
        self.FilterCompositionLabel.setText(_translate("IMXReconGUI", "Filter Composition"))
        self.PreviewReconButton.setText(_translate("IMXReconGUI", "Preview"))
        self.ImageFormaComboBox.setItemText(0, _translate("IMXReconGUI", "8 bits"))
        self.ImageFormaComboBox.setItemText(1, _translate("IMXReconGUI", "32 bits"))
        self.ImageSizeComboBox.setItemText(0, _translate("IMXReconGUI", "2048 pixels"))
        self.ImageSizeComboBox.setItemText(1, _translate("IMXReconGUI", "1024 pixels"))
        self.ImageSizeComboBox.setItemText(2, _translate("IMXReconGUI", "512 pixels"))
        self.PaddingLineEdit.setText(_translate("IMXReconGUI", "0"))
        self.PaddingLabel.setText(_translate("IMXReconGUI", "Padding"))
        self.AdjustSinoButton.setText(_translate("IMXReconGUI", "Adjust"))
        self.PositionQueue.setText(_translate("IMXReconGUI", "X"))
        self.PositionLabel.setText(_translate("IMXReconGUI", "Position:"))
        self.CleanQueueButton.setText(_translate("IMXReconGUI", "Clean All"))
        self.RemoveFromQueueButton.setText(_translate("IMXReconGUI", "Remove"))
        self.AddReconQueueButton.setText(_translate("IMXReconGUI", "ADD RECON"))
        self.QueueSettingsLabel.setText(_translate("IMXReconGUI", "Queue Settings"))
        self.menuAbout.setTitle(_translate("IMXReconGUI", "About"))
        self.actionVersion.setText(_translate("IMXReconGUI", "Version"))
        self.actionContact.setText(_translate("IMXReconGUI", "Contacts"))

import ReconGUIResource

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IMXReconGUI = QtWidgets.QMainWindow()
    ui = Ui_IMXReconGUI()
    ui.setupUi(IMXReconGUI)
    IMXReconGUI.show()
    sys.exit(app.exec_())

